import { PropsWithChildren } from "react";
import Head from "next/head";
import Image from "next/legacy/image";
import { useRouter } from "next/router";

import { signOut } from "firebase/auth";

import { FcHome, FcVip } from "react-icons/fc";
import { AiFillGithub, AiFillLinkedin } from "react-icons/ai";

import { useLayout } from "@/hooks/useLayout";

import { Container } from "./Container";
import NavLink from "./NavLink";
import { ILayout } from "@/types/typeProps";

const Layout = ({
  children,
  title = "Next App",
}: PropsWithChildren<ILayout>) => {
  const router = useRouter();
  const { currentUser, auth, setCurrentUser } = useLayout();
  function onSignOut() {
    signOut(auth);
    setCurrentUser(null);
  }
  return (
    <>
      <Head>
        <title>{title}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="./favicon.ico" />
      </Head>

      <header className="shadow-sm border-b sticky top-0 bg-white z-999999 pb-3 pt-3">
        <Container>
          <div className="flex items-center justify-between">
            <div className="flex space-x-1 sm:space-x-4 items-center">
              <div className=" hidden sm:block h-5 w-5 sm:h-9 sm:w-9 relative border-2 rounded-[5px]  border-sky-900   ">
                <Image
                  alt="logo"
                  src="https://www.cmscritic.com/wp-content/themes/cmscritic/img/cloudinary/top-social-networking-sites_wmysmq.jpg"
                  layout="fill"
                  className="  object-contain rounded"
                />
              </div>
              <nav className="flex items-center justify-between space-x-2">
                <NavLink
                  exact
                  className=" text-black flex w-[90px]  sm:w-[100px] items-center justify-center bg-sky-400 rounded-[15px] p-[4px] hover:bg-sky-500 transition-transform duration-200 ease-out"
                  href="/"
                >
                  <FcHome className="hidden sm:inline-flex  h-5 w-5 " />
                  Home
                </NavLink>

                {currentUser && (
                  <NavLink
                    className=" flex w-[90px]  sm:w-[100px] items-center justify-center bg-sky-400 rounded-[15px] p-[4px] hover:bg-sky-500 transition-transform duration-200 ease-out "
                    href="/personal"
                  >
                    <FcVip className="hidden sm:inline-flex  h-5 w-5  " />
                    Personal
                  </NavLink>
                )}
              </nav>
            </div>
            {currentUser ? (
              <div className="flex space-x-1 md:space-x-3 items-center">
                <>
                  <p className="hidden   md:block text-base">
                    {currentUser.name}
                  </p>
                  <img
                    src={currentUser.userImg}
                    alt="user-image"
                    className="h-5  sm:h-7 rounded-full "
                  />
                  <button
                    className="flex w-[90px]  sm:w-[100px]  items-center justify-center bg-sky-900 text-white rounded-[15px] p-[4px] hover:bg-sky-700 transition-transform duration-200 ease-out"
                    onClick={onSignOut}
                    type="button"
                  >
                    Sign out
                  </button>
                </>
              </div>
            ) : (
              <button
                className="flex w-[90px]  sm:w-[100px] text-white items-center justify-center bg-sky-900 rounded-[15px] p-[4px] hover:bg-sky-700 transition-transform duration-200 ease-out"
                onClick={() => router.push("/auth/signin")}
                type="button"
              >
                Sign in
              </button>
            )}
          </div>
        </Container>
      </header>

      <main>{children}</main>
      <footer className=" bg-sky-900">
        <Container>
          <div className="flex justify-between py-4">
            <div className=" h-9 w-9 relative border-2 rounded-[5px] z-1  border-white   ">
              <Image
                // priority={true}
                alt="logo"
                src="https://www.cmscritic.com/wp-content/themes/cmscritic/img/cloudinary/top-social-networking-sites_wmysmq.jpg"
                layout="fill"
                className="object-contain rounded"
              />
            </div>
            <div className="flex space-x-2 items-center">
              <a target="_blank" href="https://github.com/andrey-lawyer">
                <AiFillGithub className="text-black  w-9 h-9 bg-white border-2 rounded-[5px]  border-white hover:scale-110 transition-transform duration-200 ease-out  " />
              </a>
              <a
                className=""
                target="_blank"
                href="https://www.linkedin.com/in/andrii-uvarov/"
              >
                <AiFillLinkedin className="text-blue-600 w-9 h-9 bg-white border-2 rounded-[5px]  border-white hover:scale-110 transition-transform duration-200 ease-out  " />
              </a>
            </div>
          </div>
        </Container>
        <p className="py-2 text-white text-center border-t-[1px]">
          Copyright Ⓒ 2023 Social-network
        </p>
      </footer>
    </>
  );
};

export default Layout;
